# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra', '~> 2.1'
gem 'sinatra-websocket', '~> 0.3'
gem 'thin', '~> 1.8'    
gem 'sinatra-contrib'
gem 'activerecord',"4.2.7"
gem 'sqlite3',"1.3.13"
gem 'bigdecimal',"1.4.2"
gem 'redis'
gem 'bcrypt'

# gem "rails"

gem "webrick", "~> 1.9"
